### PR TITLE
Add sgp4.transforms converted from satellite.js

### PR DESCRIPTION
**Pull request by kannkyo**
i want to use useful utility function like satellite.js in python. so i import that.

https://github.com/shashwatak/satellite-js

### CODE REVIEW

**Comment by brandon-rhodes** [comment]
Thanks for your interest in SGP4 and making satellite data easier for Python users to access!

My guess is that this nicely compact set of routines belongs in a different library than `sgp4` itself. The intention of `sgp4` is to package up for Python programmers exactly the routines available in the official report on the algorithm:

http://www.celestrak.com/publications/AIAA/2006-6753/

It would, I fear, be misleading to start including routines from other libraries across the Internet inside of `sgp4` since those routines were not actually defined in the PDF paper linked to from the web page above.

But there are two improvements we can make to help you with your project to start porting `satellite-js` to Python:

1. First, I can review the `_gstime()` function that you need changed from private to public and see whether we can go ahead and make that change. That would allow your routines to use `sgp4` without accessing any private underscore-prefixed routines.

2. Second, I can update the documentation page for SGP4 to point out other libraries that go beyond simply implementing the standard routines defined in the Spacetrack paper by helping users associate geographic coordinates with satellite locations. I could link to Skyfield, my own library for doing so, and also link the library you create with these new routines you've written up.

I'll update this issue as I make progress on these two items. Thanks again for your interest in SGP4 and satellite tracking from Python!

**Comment by brandon-rhodes** [comment]
All right — I think I've addressed these first two shortcomings that this identified with the documentation and function names in the library. Are there other steps I can take to make SGP4 easy to use by extension routines like the ones that you are porting from JavaScript? (And: once you've released your routines as a Python module of their own, I'll be happy to link to it from the documentation right next to the link for Skyfield.)

**Comment by brandon-rhodes** [comment]
(And I hope, by the way, that you're in no way discouraged by the fact that SGP4 needs, per its mission, to remain a limited implementation of only the algorithms described in the paper — the routines you've ported are still very useful, as I regularly hear from Skyfield users who think that it's too exact and too slow to easily let them track satellites from Python. A sleeker and simpler and less fussy set of routines like the ones you've ported here from JavaScript would be a perfect complement to this `sgp4` library for folks who just want to do satellite tracking, and don't want the expense of Skyfield's exactness when it comes to defining and converting between coordinate systems!)

**Comment by kannkyo** [comment]
Thank you for your kindness reply.

I can understand your design concept of this wonderful library, sgp4. And I agree your opinion.

The reason of this pull request is my hope that access to orbital data more easily from ground segment engineer. In fact, useful, high reliability (and commercial usable) python library about orbital data are very few in the world. I searched libraries about orbital data at github, libraries.io and PyPI. sgp4 was most satisfying my request.

I will try to make my own module. This module will import and use sgp4. if  can make it, it's my first module!

Best regard.

**Comment by brandon-rhodes** [comment]
I'm going to close this for now, but please feel free to add a comment here if your library appears on PyPI; and, even as a closed PR, we can still point people at this code if we learn they need it. Thanks!

**Pull request closed without merging**
