### PR TITLE
Test for similar projected state between TLE and XML - Issue #65

### PR DESCRIPTION
**Pull request by glangford**
Test/Evaluation code - for Stations in stations.txt and the XML equivalent data published by Celestrak, create 'twin' EarthSatellite objects using each source and verify that they have a similar position at a set time. For the included TLE and XML files, the positions of all Stations are essentially identical. (This pull request originated at python-skyfield and is being moved here).

### CODE REVIEW

**Comment by brandon-rhodes** [comment]
Thank you for moving this over, and for putting together working code that from raw XML produces working satellite objects!

I plan on making several changes to the code for efficiency once it’s merged, but I don’t think it would be a good use of your time for me to force you to transform the code — you’ve provided a working prototype with a test to keep it working during any refactoring, which is a great starting point that can be merged.

If you could perform just a couple of quick pivots:

1. Could you reduce the satellite files to only 3 satellites or less? If even a single satellite is read in correctly, my guess is that all satellites will work correctly, and that it will only burn time for folks waiting for the test suite to test a whole file full.
2. Could you rename the module? Python cannot import files with a dash in the name, so your routine cannot in its present state be used by any users of `sgp4` in Python. Renaming `tle-xml.py` to something like `omm_format.py` should do the trick, and will also advertise the more official name of the format ("Orbit Mean-Elements Message", it looks like, is the expansion of the acronym).
3. As a bonus you could move the test into the `sgp4/tests.py` file, but I can merge either way and move that logic over myself.

Thanks!

**Comment by glangford** [comment]
To test the whole satellites file takes ~ 1s on my machine so I opted for completeness (given that fields and contents can vary) - but I can certainly trim it down to 3. I will also rename!

**Comment by brandon-rhodes** [comment]
> To test the whole satellites file takes ~ 1s on my machine…

The entire test suite for `sgp4` currently takes around 0.4s on my machine, so an additional second would be a large regression. When developing, I typically re-run the test suite several times per minute as I refactor code and hit "Save", so keeping the suite tight helps to keep development productive. Thanks!

**Comment by glangford** [comment]
I'm not sure how you would like the code within `sgp4/tests.py` so I left it separate, and it is ready for merge.

**Comment by brandon-rhodes** [comment]
Thanks for making those adjustments! Hopefully I'll have time to turn this into a fully documented feature within the next week or so.

**Pull request merged**
